# Generated by Django 4.1 on 2022-09-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('open_date', models.DateTimeField(auto_now_add=True)),
                ('capital', models.IntegerField()),
                ('active', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
