# Generated by Django 4.1 on 2023-02-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_alter_branch_capital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='active',
        ),
        migrations.AddField(
            model_name='branch',
            name='email',
            field=models.EmailField(default='email@mail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='branch',
            name='phone',
            field=models.CharField(default='0700000000', max_length=10),
        ),
        migrations.AddField(
            model_name='branch',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='inactive', max_length=10),
        ),
    ]
