# Generated by Django 4.1 on 2023-02-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_remove_branch_active_branch_email_branch_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='email',
            field=models.EmailField(default='email@mail.com', max_length=254, null=True),
        ),
    ]
