# Generated by Django 4.1 on 2023-02-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_alter_branch_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='branch',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
