# Generated by Django 4.1 on 2023-02-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0005_alter_branch_email_alter_branch_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='office',
            field=models.CharField(default='ABC plaza, Wayaki way, Nairobi', max_length=500),
        ),
    ]
