# Generated by Django 4.1 on 2023-02-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0006_branch_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='open_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='branch',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='Inactive', max_length=10),
        ),
    ]
