# Generated by Django 4.1 on 2023-02-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0007_alter_branch_open_date_alter_branch_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='office',
            field=models.CharField(max_length=500),
        ),
    ]
