# Generated by Django 4.1 on 2023-03-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0011_alter_expense_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='attachement',
            field=models.FileField(blank=True, null=True, upload_to='expense_attachments/'),
        ),
    ]
