# Generated by Django 4.1 on 2023-04-06 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_organization_phone_no'),
        ('branch', '0016_alter_branch_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.organization'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.organization'),
        ),
    ]
