# Generated by Django 4.1 on 2023-04-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0021_alter_branch_open_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='open_date',
            field=models.DateTimeField(),
        ),
    ]
