# Generated by Django 4.1 on 2023-05-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0023_alter_branch_open_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='open_date',
            field=models.DateTimeField(),
        ),
    ]
