# Generated by Django 4.1 on 2023-05-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0024_alter_branch_open_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
