# Generated by Django 4.1 on 2022-09-06 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit_officer',
            name='id_no',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='credit_officer',
            name='phone_no',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='credit_officer',
            name='username',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
