# Generated by Django 4.1 on 2023-04-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_branchmanager_companyadmin_creditofficer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superadmin',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='branchmanager',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=254),
        ),
        migrations.AddField(
            model_name='branchmanager',
            name='is_employee',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companyadmin',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=254),
        ),
        migrations.AddField(
            model_name='creditofficer',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=254),
        ),
        migrations.AddField(
            model_name='creditofficer',
            name='is_employee',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loginitstaff',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=254),
        ),
        migrations.AddField(
            model_name='superadmin',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=254),
        ),
        migrations.AddField(
            model_name='superadmin',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
    ]
