# Generated by Django 4.1 on 2023-04-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_companystaff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companystaff',
            options={'ordering': ['-date_added']},
        ),
        migrations.RenameField(
            model_name='companystaff',
            old_name='date_joined',
            new_name='date_added',
        ),
        migrations.AlterField(
            model_name='companystaff',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], max_length=20),
        ),
    ]
