# Generated by Django 4.1 on 2023-04-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_companystaff_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companystaff',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='active', max_length=20),
        ),
    ]
