# Generated by Django 4.1 on 2023-04-05 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_organization_remove_company_admin'),
        ('user', '0008_role_alter_companystaff_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchmanager',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.organization'),
        ),
        migrations.AlterField(
            model_name='companyadmin',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.organization'),
        ),
        migrations.AlterField(
            model_name='creditofficer',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.organization'),
        ),
    ]
