# Generated by Django 4.1 on 2023-04-06 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_organization_phone_no'),
        ('user', '0009_alter_branchmanager_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystaff',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.organization'),
        ),
    ]
