# Generated by Django 4.1 on 2023-04-06 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0016_alter_branch_company'),
        ('user', '0011_alter_companystaff_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companystaff',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='branch.branch'),
        ),
    ]
