# Generated by Django 4.1 on 2023-04-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_companystaff_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companystaff',
            name='id_no',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='companystaff',
            name='phone_no',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
