# Generated by Django 4.1 on 2023-04-11 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_organization_phone_no'),
        ('user', '0013_alter_companystaff_id_no_alter_companystaff_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.organization'),
        ),
    ]
