# Generated by Django 4.1 on 2023-04-14 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_role_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BranchManager',
        ),
    ]
