# Generated by Django 4.1 on 2023-04-14 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_delete_branchmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreditOfficer',
        ),
    ]
