# Generated by Django 4.1 on 2023-04-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_delete_creditofficer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companystaff',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
