# Generated by Django 4.1 on 2023-05-23 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_role_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companystaff',
            options={'ordering': ['-date_added'], 'permissions': [('deactivate_user', 'Can deactivate user'), ('activate_user', 'Can activate user')]},
        ),
    ]
