# Generated by Django 4.1 on 2023-05-26 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0022_alter_organization_phone_no'),
        ('user', '0024_recentactivity_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.organization')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.companystaff')),
            ],
        ),
    ]
