# Generated by Django 4.1 on 2022-09-06 12:35

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_name', models.CharField(max_length=300)),
                ('loan_term', models.PositiveSmallIntegerField()),
                ('repayment_frequency', models.CharField(choices=[('onetime', 'ONETIME'), ('daily', 'DAILY'), ('weekly', 'WEEKLY'), ('monthly', 'MONTHLY')], default='onetime', max_length=8)),
                ('interest_type', models.CharField(choices=[('flat_rate', 'FLAT RATE'), ('reducing_balance', 'REDUCING BALANCE')], default='flat_rate', max_length=30)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('interest_rate_per', models.CharField(choices=[('day', 'DAY'), ('month', 'MONTH'), ('year', 'YEAR')], default='month', max_length=50)),
                ('service_fee_type', models.CharField(choices=[('fixed_value', 'FIXED VALUE'), ('percentage_of_principal', 'PERCENTAGE OF PRINCIPAL')], default='fixed_value', max_length=300)),
                ('service_fee_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('penalty_type', models.CharField(choices=[('fixed_value', 'FIXED VALUE'), ('percentage_of_principal', 'PERCENTAGE OF PRINCIPAL'), ('percentage_of_principal', 'PERCENTAGE OF PRINCIPAL')], default='fixed_value', max_length=300)),
                ('penalty_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('penalty_frequency', models.CharField(choices=[('onetime', 'ONETIME'), ('daily', 'DAILY'), ('weekly', 'WEEKLY'), ('monthly', 'MONTHLY')], default='fixed_value', max_length=300)),
            ],
        ),
    ]
