# Generated by Django 4.1 on 2022-09-06 13:28

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanproduct',
            name='penalty_type',
            field=models.CharField(choices=[('fixed_value', 'FIXED VALUE'), ('percentage_of_principal', 'p.c of Due Principal'), ('percentage_of_principal_interest', 'p.c of Due P + I')], default='fixed_value', max_length=300),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='penalty_value',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='service_fee_type',
            field=models.CharField(choices=[('fixed_value', 'FIXED VALUE'), ('percentage_of_principal', 'p.c of Principal')], default='fixed_value', max_length=300),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='service_fee_value',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
