# Generated by Django 4.1 on 2022-09-06 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_member_id_no_alter_member_phone_no'),
        ('user', '0002_alter_credit_officer_id_no_and_more'),
        ('loan', '0002_alter_loanproduct_penalty_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('loan_purpose', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('credit_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.credit_officer')),
                ('id_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='national_id_no', to='member.member')),
                ('interest_rate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interest_rate_applied', to='loan.loanproduct')),
                ('loan_term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_term_applied', to='loan.loanproduct')),
                ('loan_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loan.loanproduct')),
                ('member_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.member')),
                ('mobile_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_mob_no', to='member.member')),
                ('payment_frequency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_frequency', to='loan.loanproduct')),
            ],
            options={
                'ordering': ['-updated', '-application_date'],
            },
        ),
    ]
