# Generated by Django 4.1 on 2023-02-22 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.ForeignKey(default=0.3, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interest_rate_applied', to='loan.loanproduct'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_term',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_term_applied', to='loan.loanproduct'),
        ),
    ]
