# Generated by Django 4.1 on 2023-02-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_alter_loan_interest_rate_alter_loan_loan_term'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanproduct',
            old_name='loan_name',
            new_name='loan_product_name',
        ),
        migrations.RenameField(
            model_name='loanproduct',
            old_name='loan_term',
            new_name='loan_product_term',
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='loan_product_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='maximum_amount',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='minimum_amount',
            field=models.IntegerField(default=5000),
        ),
    ]
