# Generated by Django 4.1 on 2023-02-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_rename_loan_name_loanproduct_loan_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_id',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
