# Generated by Django 4.1 on 2023-02-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_loan_loan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_id',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
    ]
