# Generated by Django 4.1 on 2023-02-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0007_alter_loan_loan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='id_no',
            field=models.CharField(max_length=10),
        ),
    ]
