# Generated by Django 4.1 on 2023-02-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0008_alter_loan_id_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_term',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='loan',
            name='member_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='loan',
            name='mobile_no',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='loan',
            name='payment_frequency',
            field=models.CharField(max_length=50),
        ),
    ]
