# Generated by Django 4.1 on 2023-03-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0010_remove_loanproduct_interest_rate_per_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanproduct',
            name='interest_type',
            field=models.CharField(choices=[('flat rate', 'FLAT RATE'), ('reducing balance', 'REDUCING BALANCE')], default='flat_rate', max_length=30),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='penalty_type',
            field=models.CharField(choices=[('fixed_value', 'FIXED VALUE'), ('percentage of principal', 'p.c of Due Principal'), ('percentage of principal interest', 'p.c of Due P + I')], default='fixed_value', max_length=300),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='service_fee_type',
            field=models.CharField(choices=[('fixed value', 'FIXED VALUE'), ('percentage of principal', 'p.c of Principal')], default='fixed_value', max_length=300),
        ),
    ]
