# Generated by Django 4.1 on 2023-03-03 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_member_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        #('user', '0002_alter_credit_officer_id_no_and_more'),
        ('loan', '0011_alter_loanproduct_interest_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['application_date']},
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='interest_rate',
            new_name='applied_amount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='id_no',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loan_term',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loan_type',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='member_name',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='mobile_no',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='payment_frequency',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='updated',
        ),
        migrations.AddField(
            model_name='loan',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='attachments'),
        ),
        migrations.AddField(
            model_name='loan',
            name='guarantor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.member'),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loan.loanproduct'),
        ),
        migrations.AddField(
            model_name='loan',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_as_member', to='member.member'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='application_date',
            field=models.DateTimeField(),
        ),
        
      #  migrations.AlterField(
       #     model_name='loan',
       #     name='credit_officer',
       #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_as_guarantor', to='user.credit_officer'), 
       # ), 
    ]
