# Generated by Django 4.1 on 2023-03-03 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_member_email'),
        ('loan', '0012_alter_loan_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='credit_officer',
        ),
        migrations.AlterField(
            model_name='loan',
            name='guarantor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_as_guarantor', to='member.member'),
        ),
    ]
