# Generated by Django 4.1 on 2023-03-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0013_remove_loan_credit_officer_alter_loan_guarantor'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('approved', 'APPROVED'), ('cancelled', 'CANCELLED'), ('overdue', 'OVERDUE'), ('cleared', 'CLEARED')], default='pending', max_length=50),
        ),
    ]
