# Generated by Django 4.1 on 2023-03-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0014_loan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='application_date',
            field=models.DateField(),
        ),
    ]
