# Generated by Django 4.1 on 2023-03-08 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0020_alter_note_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('date_paid', models.DateTimeField()),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.loan')),
            ],
            options={
                'ordering': ['-date_paid'],
            },
        ),
    ]
