# Generated by Django 4.1 on 2023-03-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0021_repayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repayment',
            name='date_paid',
            field=models.DateField(),
        ),
    ]
