# Generated by Django 4.1 on 2023-03-08 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_member_email'),
        ('loan', '0022_alter_repayment_date_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='repayment',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.member'),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='loan_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loan.loan'),
        ),
    ]
