# Generated by Django 4.1 on 2023-03-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0023_repayment_member_alter_repayment_loan_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-application_date']},
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='interest_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='loan_product_term',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='penalty_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='service_fee_value',
            field=models.FloatField(),
        ),
    ]
