# Generated by Django 4.1 on 2023-03-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0028_alter_loan_guarantor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='loan_attachments/'),
        ),
    ]
