# Generated by Django 4.1 on 2023-03-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0030_guarantor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarantor',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
