# Generated by Django 4.1 on 2023-03-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0033_collateral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collateral',
            name='type',
            field=models.CharField(choices=[('electronics', 'ELECTRONICS'), ('vehicle', 'VEHICLE'), ('land', 'LAND'), ('shares', 'SHARES'), ('cash deposit', 'CASH DEPOSIT'), ('others', 'OTHERS')], default='others', max_length=50),
        ),
    ]
