# Generated by Django 4.1 on 2023-04-06 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_organization_phone_no'),
        ('loan', '0039_loan_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.organization'),
        ),
    ]
