# Generated by Django 4.1 on 2023-04-06 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_organization_phone_no'),
        ('loan', '0040_alter_loan_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='repayment',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.organization'),
        ),
    ]
