# Generated by Django 4.1 on 2023-04-06 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_branchmanager_company_and_more'),
        ('loan', '0042_alter_repayment_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.companystaff'),
        ),
    ]
