# Generated by Django 4.1 on 2023-04-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0043_alter_loan_loan_officer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanproduct',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='active', max_length=10),
        ),
    ]
