# Generated by Django 4.1 on 2023-04-11 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_organization_phone_no'),
        ('loan', '0044_alter_loanproduct_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='collateral',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.organization'),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.organization'),
        ),
        migrations.AddField(
            model_name='note',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.organization'),
        ),
        migrations.AlterField(
            model_name='collateral',
            name='loan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loan.loan'),
        ),
        migrations.AlterField(
            model_name='note',
            name='loan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loan.loan'),
        ),
    ]
