# Generated by Django 4.1 on 2023-04-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0046_alter_collateral_name_alter_collateral_serial_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='approved_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='disbursed_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
