# Generated by Django 4.1 on 2023-04-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0047_loan_approved_amount_loan_disbursed_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='cleared_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='disbursed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='service_fee_type',
            field=models.CharField(choices=[('fixed value', 'FIXED VALUE'), ('percentage', 'PERCENTAGE')], default='fixed_value', max_length=300),
        ),
    ]
