# Generated by Django 4.1 on 2023-04-21 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_companystaff_password'),
        ('loan', '0048_loan_cleared_date_loan_disbursed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_as_manager', to='user.companystaff'),
        ),
        migrations.AddField(
            model_name='loan',
            name='approved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_as_officer', to='user.companystaff'),
        ),
    ]
