# Generated by Django 4.1 on 2023-04-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0049_loan_approved_by_loan_approved_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='application_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='cleared_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='disbursed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
