# Generated by Django 4.1 on 2023-04-28 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_organization_phone_no'),
        ('member', '0028_alter_member_previous_credit_score'),
        ('loan', '0051_alter_repayment_loan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repayment',
            name='date_paid',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='MpesaStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('statements', models.FileField(blank=True, null=True, upload_to='mpesa-statements/')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.organization')),
                ('loan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loan.loan')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
        ),
    ]
