# Generated by Django 4.1 on 2023-04-29 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0052_alter_repayment_date_paid_mpesastatement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesastatement',
            name='loan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='loan.loan'),
        ),
    ]
