# Generated by Django 4.1 on 2023-05-02 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0054_loan_amount_credit_s_loan_amount_mpesa_s'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='amount_credit_s',
        ),
    ]
