# Generated by Django 4.1 on 2023-05-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0055_remove_loan_amount_credit_s'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='due_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='num_installments',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
