# Generated by Django 4.1 on 2023-05-04 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0056_loan_due_amount_loan_due_date_loan_num_installments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='due_amount',
        ),
    ]
