# Generated by Django 4.1 on 2023-05-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0058_loan_due_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanproduct',
            name='maximum_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='minimum_amount',
            field=models.IntegerField(),
        ),
    ]
