# Generated by Django 4.1 on 2023-05-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0059_alter_loanproduct_maximum_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='write_off_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='write_off_expense',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('approved', 'APPROVED'), ('rejected', 'REJECTED'), ('overdue', 'OVERDUE'), ('cleared', 'CLEARED'), ('written off', 'WRITTEN OFF')], default='pending', max_length=50),
        ),
    ]
