# Generated by Django 4.1 on 2023-05-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0060_loan_write_off_date_loan_write_off_expense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('approved', 'APPROVED'), ('rejected', 'REJECTED'), ('overdue', 'OVERDUE'), ('cleared', 'CLEARED'), ('written off', 'WRITTEN OFF'), ('rolled over', 'ROLLED OVER')], default='pending', max_length=50),
        ),
    ]
