# Generated by Django 4.1 on 2023-05-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0062_loan_parent_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='final_due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
