# Generated by Django 4.1 on 2023-05-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0063_loan_final_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='interest_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='service_fee_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
