# Generated by Django 4.1 on 2023-05-29 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0065_alter_loan_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='amount_mpesa_s',
        ),
    ]
