# Generated by Django 4.1 on 2023-06-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0068_loan_been_penalized_alter_loan_loan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='applied_amount',
            field=models.IntegerField(),
        ),
    ]
