# Generated by Django 4.1 on 2023-07-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0069_alter_loan_applied_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
