# Generated by Django 4.1 on 2023-04-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_delete_company_organization_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='phone_no',
            field=models.CharField(default='0712345678', max_length=10),
        ),
    ]
