# Generated by Django 4.1 on 2023-04-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_organization_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_license_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='status',
            field=models.CharField(default='active', max_length=30),
        ),
       
    ]
  
  