# Generated by Django 4.1 on 2023-04-29 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_organization_is_license_expired_organization_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('annual_price', models.CharField(max_length=100)),
                ('monthly_price', models.CharField(max_length=100)),
                ('employees', models.CharField(max_length=100)),
                ('storage', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to='company.package', null=True),

        ),
    ]
