# Generated by Django 4.1 on 2023-05-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_organization_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='shortcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
