# Generated by Django 4.1 on 2023-05-12 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_organization_shortcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='shortcode',
        ),
        migrations.CreateModel(
            name='SmsSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(blank=True, max_length=15, null=True)),
                ('api_token', models.CharField(blank=True, max_length=200, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.organization')),
            ],
        ),
    ]
