# Generated by Django 4.1 on 2023-05-12 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_remove_organization_shortcode_smssetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortcode', models.CharField(blank=True, max_length=15, null=True)),
                ('app_consumer_key', models.CharField(blank=True, max_length=200, null=True)),
                ('app_consumer_secret', models.CharField(blank=True, max_length=200, null=True)),
                ('online_passkey', models.CharField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(blank=True, max_length=15, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.organization')),
            ],
        ),
        migrations.CreateModel(
            name='EmailSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_name', models.CharField(blank=True, max_length=15, null=True)),
                ('from_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('smtp_host', models.CharField(blank=True, max_length=200, null=True)),
                ('encryption', models.CharField(choices=[('tls', 'TLS'), ('ssl', 'SSL'), ('none', 'NONE')], default='tls', max_length=10)),
                ('port', models.CharField(choices=[('tls', 'TLS'), ('ssl', 'SSL'), ('none', 'NONE')], default='tls', max_length=10)),
                ('app_consumer_secret', models.CharField(blank=True, max_length=200, null=True)),
                ('smtp_username', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.organization')),
            ],
        ),
    ]
