# Generated by Django 4.1 on 2023-05-12 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_remove_emailsetting_port'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailsetting',
            old_name='password',
            new_name='smtp_password',
        ),
    ]
