# Generated by Django 4.1 on 2023-05-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_rename_password_emailsetting_smtp_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesasetting',
            name='shortcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
