# Generated by Django 4.1 on 2023-05-13 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_remove_emailsetting_app_consumer_secret_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailsetting',
            old_name='smpt_port',
            new_name='smtp_port',
        ),
    ]
