# Generated by Django 4.1 on 2023-05-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_rename_smpt_port_emailsetting_smtp_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='organization',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
