# Generated by Django 4.1 on 2023-05-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_organization_currency_organization_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='country',
            field=models.CharField(default='Kenya', max_length=30),
        ),
    ]
