# Generated by Django 4.1 on 2023-05-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0021_organization_phone_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='phone_no',
            field=models.CharField(default='712345678', max_length=12),
        ),
    ]
