# Generated by Django 4.1 on 2023-05-29 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_systemsetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemsetting',
            old_name='is_disburse',
            new_name='is_auto_disburse',
        ),
    ]
