# Generated by Django 4.1 on 2023-06-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0024_rename_is_disburse_systemsetting_is_auto_disburse'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='send_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='send_sms',
            field=models.BooleanField(default=False),
        ),
    ]
