# Generated by Django 4.1 on 2023-06-20 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0025_systemsetting_send_email_systemsetting_send_sms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemsetting',
            old_name='send_email',
            new_name='is_send_email',
        ),
        migrations.RenameField(
            model_name='systemsetting',
            old_name='send_sms',
            new_name='is_send_sms',
        ),
    ]
