# Generated by Django 4.1 on 2023-07-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0029_smstemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='smssetting',
            name='member_welcome',
            field=models.TextField(default='Dear member_name, welcome to our microfinance'),
        ),
    ]
