# Generated by Django 4.1 on 2023-07-12 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0030_smssetting_member_welcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_welcome', models.TextField(default='Dear member_name, welcome to our microfinance')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.organization')),
            ],
        ),
    ]
