# Generated by Django 4.1 on 2023-07-12 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0031_templatesetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smssetting',
            name='member_welcome',
        ),
    ]
