# Generated by Django 4.1 on 2023-07-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0033_templatesetting_loan_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatesetting',
            name='loan_approved',
            field=models.TextField(default='Dear member_name, your application is under review'),
        ),
        migrations.AddField(
            model_name='templatesetting',
            name='loan_balance',
            field=models.TextField(default='Dear member_name, welcome to our microfinance'),
        ),
        migrations.AddField(
            model_name='templatesetting',
            name='loan_cleared',
            field=models.TextField(default='Dear member_name, welcome to our microfinance'),
        ),
        migrations.AddField(
            model_name='templatesetting',
            name='loan_overdue',
            field=models.TextField(default='Dear member_name, your application is under review'),
        ),
        migrations.AddField(
            model_name='templatesetting',
            name='loan_rejected',
            field=models.TextField(default='Dear member_name, welcome to our microfinance'),
        ),
        migrations.AddField(
            model_name='templatesetting',
            name='loan_rolled_over',
            field=models.TextField(default='Dear member_name, your application is under review'),
        ),
    ]
