# Generated by Django 4.1 on 2023-07-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0035_alter_templatesetting_member_welcome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatesetting',
            name='loan_rolled_over',
        ),
        migrations.AddField(
            model_name='templatesetting',
            name='after_payment',
            field=models.TextField(default='Dear {first_name}, your next payment is on {due_date}. Due amount: {currency}{due_amount} . Loan balance: {currency}{loan_balance}. Acc. no: {account_no} Paybill:{paybill_no}'),
        ),
        migrations.AlterField(
            model_name='templatesetting',
            name='loan_applied',
            field=models.TextField(default='Dear {first_name} {last_name}, Your loan request as been received and its under review. Regards {organization_name}'),
        ),
        migrations.AlterField(
            model_name='templatesetting',
            name='loan_approved',
            field=models.TextField(default='Dear {first_name}, Your loan request has been approved and queued for disbursal. The next payment date {due_date}, amount {currency}{due_amount}. Acc. {account_no} Paybill {paybill_no}'),
        ),
        migrations.AlterField(
            model_name='templatesetting',
            name='loan_balance',
            field=models.TextField(default='Dear {first_name}, your next payment is on {due_date}. Due amount: {currency}{due_amount} . Loan balance: {currency}{loan_balance}. Acc. No: {account_no} Paybill:{paybill_no}'),
        ),
        migrations.AlterField(
            model_name='templatesetting',
            name='loan_cleared',
            field=models.TextField(default='Dear {first_name} {last_name}, You have successfully cleared your loan. Success in your business. {organization_name}'),
        ),
        migrations.AlterField(
            model_name='templatesetting',
            name='loan_overdue',
            field=models.TextField(default='Dear {first_name}, your loan installment of {currency}{due_amount} is overdue. Make payment to avoid further penalties. Acc. no: {account_no} Paybill:{paybill_no}'),
        ),
        migrations.AlterField(
            model_name='templatesetting',
            name='loan_rejected',
            field=models.TextField(default='Dear {first_name}, we regret to inform you that we are unable to approve your loan request of {currency}{applied_amount} at this time. '),
        ),
    ]
