# Generated by Django 4.1 on 2023-07-12 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0036_remove_templatesetting_loan_rolled_over_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SmsTemplate',
        ),
    ]
