# Generated by Django 4.1 on 2023-07-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0037_delete_smstemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='account_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='paybill_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
