# Generated by Django 4.1 on 2023-02-23 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_alter_branch_capital'),
        ('member', '0002_alter_member_id_no_alter_member_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='branch.branch'),
        ),
        migrations.AddField(
            model_name='member',
            name='business_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='industry',
            field=models.CharField(choices=[('beauty', 'BEAUTY'), ('hospitality', 'HOSPITALITY'), ('retail', 'RETAIL'), ('skilled', 'SKILLED'), ('others', 'OTHERS')], max_length=500, null=True),
        ),
    ]
