# Generated by Django 4.1 on 2023-02-23 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_member_branch_member_business_name_member_industry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='business_type',
            new_name='description',
        ),
    ]
