# Generated by Django 4.1 on 2023-03-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_rename_business_type_member_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='description',
        ),
        migrations.AddField(
            model_name='member',
            name='credit_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
