# Generated by Django 4.1 on 2023-03-17 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_alter_member_first_name_alter_member_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-date_joined']},
        ),
    ]
