# Generated by Django 4.1 on 2023-03-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_member_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='passport_photo',
            field=models.ImageField(default='/static/images/pp-image-placeholder.png', upload_to=''),
        ),
    ]
