# Generated by Django 4.1 on 2023-03-23 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0019_alter_member_passport_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['date_joined']},
        ),
    ]
