# Generated by Django 4.1 on 2023-03-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0020_alter_member_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-date_joined']},
        ),
        migrations.AlterField(
            model_name='member',
            name='date_joined',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='passport_photo',
            field=models.ImageField(upload_to='member_passports/'),
        ),
    ]
