# Generated by Django 4.1 on 2023-03-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0021_alter_member_options_alter_member_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date_joined',
            field=models.DateTimeField(),
        ),
    ]
