# Generated by Django 4.1 on 2023-03-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0022_alter_member_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date_joined',
            field=models.DateField(),
        ),
    ]
