# Generated by Django 4.1 on 2023-03-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0023_alter_member_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='passport_photo',
            field=models.ImageField(default='default.png', upload_to='member_passports/'),
        ),
    ]
