# Generated by Django 4.1 on 2023-04-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0026_alter_member_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='previous_credit_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
