# Generated by Django 4.1 on 2023-04-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0027_member_previous_credit_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='previous_credit_score',
            field=models.IntegerField(default=0),
        ),
    ]
