# Generated by Django 4.1 on 2023-05-09 08:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0029_alter_member_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='id_no',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(12)]),
        ),
    ]
