# Generated by Django 4.1 on 2023-05-09 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0031_alter_member_id_no_alter_member_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone_no',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.MinValueValidator(12)]),
        ),
    ]
