# Generated by Django 4.1 on 2023-05-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0033_alter_member_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date_joined',
            field=models.DateTimeField(),
        ),
    ]
